### ISSUE TITLE
Still can't download themes individually

### ISSUE THREAD

**Issue by ghost** [Flerp/RetroCake#1]
Trying to download certain themes (snes-mini) just crash the prompt. So far the only theme that hasn't crashed the prompt has been pixel-metadata.

**Comment by Flerp** [comment]
Seems like pages 1 and 2 work, but everything after crashes. Working on debugging now.

**Comment by Flerp** [comment]
Fixed the issue!

Some lines had goto goto snes-mini instead of just goto snes-mini.
