### ISSUE TITLE
Can't add SplashScreens

### ISSUE THREAD

**Issue by ProtoBoyGG** [Flerp/RetroCake#11]
Hi! I'm  unable to add splash screen also "loading game" screen that are often seen in retropie though i have them.

where are they supposed to be placed or can you design something to get a splash and a loading game screen ?

**Comment by Flerp** [comment]
Unfortunately since RetroCake launches directly to RetroArch or another emulator I don't believe it's currently possible. I will look into it, but I have had absolutely 0 time to work on this project in the last few months sadly.
