### ISSUE TITLE
Default PS1 core is PCSX-reARMed

### ISSUE THREAD

**Issue by darrena092** [Flerp/RetroCake#12]
This is a bit of a problem IMO. PCSX-reARMed obviously doesn't work on x86 CPUs and this is meant to target Windows as the primary platform.

I would say that there's a strong argument to switch the default to something like Beetle-PSX - as this is likely to be a point of confusion for some.

**Comment by wonx** [comment]
I installed RetroCake today to be able to play PSX games on my tablet. How can I change the default emulator?
