### ISSUE TITLE
Update your link

### ISSUE THREAD

**Issue by XxsjrapsxX** [Flerp/RetroCake#16]
it says to tell flerp to update the link

**Comment by skankware** [comment]
I, too, have been instructed to inform you that a link needs updating. Specifically the one having to do with "7za" or something like that.

**Comment by harcocjh** [comment]
Yes, also trying to run this and it says to yell at you to update the URL. lol Thanks!

**Comment by harcocjh** [comment]
So just a quick update...if you just hit enter when it asks you to put in the install directory it will give you this error. I thought by leaving it blank it would just use the default C:\RetroCake but nope you have to type that out. So go into %appdata%\roaming and delete the retrocake folder to reset everything and then run it again and actually type out the install path to either C:\RetroCake or wherever you want. Should work then!

**Comment by Flerp** [comment]
So...It's been a little while
Wget URLs are permanently fixed.

As for the custom directory causing tool download issues I am currently investigating.
