### ISSUE TITLE
Themes update

### ISSUE THREAD

**Issue by u1735067** [Flerp/RetroCake#17]
Hello, 

there's changes in some themes : 
* ChoccyHobNob/es-theme-eudora-updated is down
* InsecureSpike/es-theme-retroplay-clean-canela is now InsecureSpike/es-theme-clean-simple-canela (branch v3.0-update)
* InsecureSpike/es-theme-retroplay-clean-detail-canela is now InsecureSpike/es-theme-clean-detail-canela (branch v3.0-update)

Best,

**Comment by Flerp** [comment]
Stubbed eudora-updated.

As for the the canela themes I am currently leaving them until EmulationStation hits 3.0 on Windows
