### ISSUE TITLE
Triggers Windows Defender

### ISSUE THREAD

**Issue by sivan-koren** [Flerp/RetroCake#2]
Triggers Windows Defender, which makes it difficult to download.

**Comment by Flerp** [comment]
Removed EXE :<

**Comment by harryjubb** [comment]
From the release EXE I am getting in Windows Defender:

```
Trojan:Win32/Tiggre!plock
Alert level: Severe

[...]

Recommended action: Remove the threat now.

Category: Trojan
Details: This program is dangerous and executes commands from an attacker.
```

With a link to the [threat page](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fTiggre!plock&threatid=2147723626).

This is obviously quite concerning.

Is there a reason that this happens?
