### ISSUE TITLE
Do you know Retrobat ?

### ISSUE THREAD

**Issue by lehcimcramtrebor** [Flerp/RetroCake#20]
Hello, do you know Retrobat ?

https://www.retrobat.ovh/contact_en.html

**Comment by Flerp** [comment]
Nope, haven't heard of it

**Comment by lehcimcramtrebor** [comment]
Hello, I am French theme creator for batocera and retrobat, a year ago I
used retrocake.. Retrobat have batocera collaboration with an
emulationstation very advanced, so we have just got animations now..you
should test it.. there is a group on Facebook.
