### ISSUE TITLE
ES breaks

### ISSUE THREAD

**Issue by dobbleg1000** [Flerp/RetroCake#3]
If the latest emulation station build fails it fails to install es. Which is an issue for first installations.

**Comment by Flerp** [comment]
Hi, can you check if wget.exe exists in C:\RetroCake\Tools\Wget\
Want to see if wget is not installing properly

**Comment by dobbleg1000** [comment]
It does. Everything else worked but the link it wanted (I read through the script) didnt exist because the builds were failing.

**Comment by dobbleg1000** [comment]
I got it to work by failing back to 2.2.2.220 which could be an option for initial installs.

**Comment by Flerp** [comment]
I created a fallback for ES 2.8.0 in case the current builds are failing.
It checks emulationstation.exe so it bay not be 100% reliable. 
This should be okay until I can think of a better implementation.
I'm leaving the issue open as I do not have time to test yet, but I'll close it once I have tested.
