### ISSUE TITLE
Scrapped games reset

### ISSUE THREAD

**Issue by FirionHope** [Flerp/RetroCake#5]
Not sure if this is specific to retrocake, but when I go to scrape games and restart emulation station most games will revert back to unscraped. I have save metadata on exit on

**Comment by Flerp** [comment]
Hi, I cannot replicate the issue, myself on emulationStation 2.8.0-RP
What version of EmulationStation do you currently have, Which windows (7, 8, 8.1, 10), and which architecture (32 bit vs 64 bit)?
I have a test environment I use for each OS and architecture.

**Comment by Flerp** [comment]
As I cannot replicate the issue and there seems to be no further replies I will be closing this issue.
Feel free to reopen if the issue happens again.
