### ISSUE TITLE
Unable to install any version of Emulationstation

### ISSUE THREAD

**Issue by ghost** [Flerp/RetroCake#6]
I'm trying to install the program in C:\Program Files\RetroCake but when I press 1 to install it creates in C:\ two files called program and program.7z
In C:\Program Files\RetroCake\Tools\wget there is nothing and I get the error ""C: \Program Files\ RetroCake"\Tools\Wget\ wget.exe" is not recognized as an internal or external command,
an executable program or a batch file.
![error](https://user-images.githubusercontent.com/25184655/43930250-b621f5aa-9c38-11e8-8145-cfd3ac3480f6.PNG)

**Comment by djwyman** [comment]
I was having this problem too and it was kicking my butt.  Start up the retrocake.bat then when you get to the main menu pick 7 for system clean up.  then pick 1. remove all retrocake files.  after you do that exit out of the retrocake installer and start it up again.  Now for the first question press N. then you can run the installer and it will go threw.

**Comment by Rodro150** [comment]
Same issue, what djwyman said didn't work.

**Comment by Cr4sHBR** [comment]
I resolve this issue downloading wget.exe from (https://eternallybored.org/misc/wget/) and put in C:\RetroCake\Tools\Wget
then, run retrocake.bat again.

**Comment by Flerp** [comment]
Added better error handling to resolve the vague failed download issues.
