### ISSUE TITLE
Controller configuration issue

### ISSUE THREAD

**Issue by NoeleyC** [Flerp/RetroCake#7]
I've installed Retrocake on my GPD Win 2, its controller identifies itself as a Xbox 360 controller but I'm unable to use all the shoulder buttons on my device. I can add the shoulder buttons, but the emulator doesn't recognise my trigger buttons. Is this a known issue with X-input type controllers?

**Comment by Flerp** [comment]
I haven't run into this issue, but this may shed some light on it.
Unlike RetroPie, binding controllers in EmulationStation (The main ROM launcher) does not bind controls for your emulators.
Retroarch emulators do a pretty good job of auto configuring controllers, and I've had great results with xinput (xbox 360 and xbox one controllers), but binding controls much be done either from within retroarch (Hitting Start + Select in a game) or in whichever additional emulator has been launched.

As a side note, The bumpers don't seem to work inside EmulationStation. I believe this is a side effect of Emulationstation, coded for RaspberryPi/Debian based distros, being compiled for Windows.

**Comment by NoeleyC** [comment]
Thanks for the update on this, that does seem to clarify matters pretty much! I have managed to further configure controllers within Retroarch itself. The shoulder buttons issue is only most apparent to me as it's useful in Retropie for scrolling fast through long lists of roms. Other than that it's all working great, still have to sort out Amiga emulation through it (never really used P-UAE before).
