### ISSUE TITLE
Updater Fails

### ISSUE THREAD

**Issue by dobbleg1000** [Flerp/RetroCake#8]
If RetroCake is installed on another drive and you Run as Admin it fails.
The reason being is Run as Admin starts in 
C:\Windows\System32 
and the Script attempts to just cd to the directory. But in Windows to access another drive you must first run
D:
then 
cd D:\whatever\path\you\want

This happens in ESCheck
put this before the cd
%rkdir:~0,2%

**Comment by dobbleg1000** [comment]
Looks to be fixed already

**Comment by NoeleyC** [comment]
I still have this issue on my setup too. I have my Retrocake install and files all on my D drive, and the updater falls over as detailed above

**Comment by Flerp** [comment]
I have fixed up the alternate drive installation now
